## 1

(a)

In [1]:
from numpy import array,zeros,linalg,empty,copy

In [2]:
U=array([[-5  ,2 ,0, -2 ,-3],[0, 1, 0, -5, 4],[0, 0, 1, -1, 1
],[0, 0, 0, 4, -2],[0, 0, 0, 0, 4]],float)
L=array([[1, 0, 0, 0, 0],[3, 1, 0, 0, 0],[0, 2, 1, 0, 0],[2, 2, -4, 1, 0],[5, -4, -3, -2, 1]],float)
bt=array([2,
-3,
-3,
2,
3],float)


In [3]:
A=[]
for i in range(5):
    a=[]
    for j in range(5):
        b=0.0
        for k in range(5):
            b+=L[i,k]*U[k,j]
        a.append(b)
    A.append(a)           
print(A)   

[[-5.0, 2.0, 0.0, -2.0, -3.0], [-15.0, 7.0, 0.0, -11.0, -5.0], [0.0, 2.0, 1.0, -11.0, 9.0], [-10.0, 6.0, -4.0, -6.0, -4.0], [-25.0, 6.0, -3.0, 5.0, -26.0]]


In [4]:
print('xtest=',linalg.solve(A,bt))

xtest= [-27.5   28.25  14.75  38.25  38.5 ]


(b)

$\textbf{A}x=b$
Then, 
$\textbf{LU}x=b$
 set $\textbf{U}x=c$
 then $\textbf{L}c=b$
 solve for c and solve for x

In [5]:
def LUsolver(A,B,b):
    N=len(b)
    c=empty(N,float)
    for i in range(0,N):
        c[i]=b[i]
        for j in range(i-1,-1,-1):
            c[i]-=A[i,j]*c[j]
     
    N=len(c) 
    x=empty(N,float)
    for i in range(N-1,-1,-1):
        x[i]=c[i]/B[i,i]
        for j in range(i+1,N):
            x[i]-=((B[i,j])*x[j])/B[i,i]
    print(x)
   

In [6]:
LUsolver(L,U,bt)


[-27.5   28.25  14.75  38.25  38.5 ]


(c)

$\textbf{U}\textbf{U}^{-1}=\textbf{I}$,

$\textbf{L}\textbf{L}^{-1}=\textbf{I}$,

$\textbf{A}\textbf{A}^{-1}=\textbf{I}$,

Then,
$$\textbf{A}^{-1}=\textbf{U}^{-1}\textbf{L}^{-1}$$

Taking the columns of $\textbf{U}^-1$ and $\textbf{L}^-1$ as individual solution vectors with corresponding $\textbf{I}$ basis columns:
$\textbf{U}[u^{-1}_{1}......u^{-1}_{n}]=[I_1,I_2......I_n]$

In [7]:
I=array([[1,0,0,0,0],[0,1,0,0,0],[0,0,1,0,0],[0,0,0,1,0],[0,0,0,0,1]],float)

In [8]:
def inverse(A,B):
    N=len(I)
    invL=empty([N,N],float)
    for k in range(len(I)):
        for i in range(0,N):
            invL[k][i]=I[k,i]
            for j in range(i-1,-1,-1):
                invL[k][i]-=A[i,j]*invL[k][j]
    
    
    invU=empty([N,N],float)
    for k in range(len(I)):
        for i in range(N-1,-1,-1):
            invU[k][i]=I[k,i]/B[i,i]
            for j in range(i+1,N):
                invU[k][i]-=(B[i,j]*invU[k][j])/B[i,i]
    
    
    inv=[]
    for i in range(N):
        a=[]
        for j in range(N):
            b=0.0
            for k in range(N):
                b+=invU.T[i,k]*invL.T[k,j]
            a.append(b)
        inv.append(a)           
    print(inv) 
    
    
    

In [9]:
inverse(L,U)

[[-10.149999999999999, 4.1, -2.2499999999999996, -0.29999999999999993, -0.35], [10.625, -3.25, 0.875, 0.5, -0.375], [5.875, -1.75, 0.625, 0.0, -0.125], [14.125, -5.25, 2.375, 0.5, 0.125], [14.25, -5.5, 2.75, 0.5, 0.25]]


## 2

(a)

$I_{+3}=I_{34}+I_{31} \rightarrow 5=-V_{1}+3V_{3}-V_{4} $,

$I_{+1}=I_{13}+I_{14}+I_{12} \rightarrow 5=4V_{1}-V_{2}-V_{3}-V_{4}$,

$I_{20}=I_{12}+I_{42} \rightarrow 0=V_{1}-3V_{2}+V_{4}$,

$I_{40}=I_{14}+I_{34}+I_{24} \rightarrow 0=V_{1}+V_{2}+V_{3}-4V_{4}$

Then $\textbf{A}$:
$$ \begin{pmatrix}
-1 & 0 & 3 & -1\\
4 & -1 & -1 & -1 \\
1 & 1 & 1 & -4\\
1 & -3 & 0 & 1 \\
\end{pmatrix}
\begin{pmatrix}
V_{1} \\
V_{2}\\
V_{3}\\
V_{4}
\end{pmatrix}=\begin{pmatrix}
5 \\
5\\
0\\
0
\end{pmatrix}$$



In [10]:
V=array([[1,1,1,-4],[4,-1,-1,-1],[-1,0,3,-1],[1,-3,0,1]],float)
b1=array([0,5,5,0],float)

In [11]:
N=len(b1)
#I could have added the pivoting routine but I think it works regardless

    
for i in range(N):
    a=V[i,i]
    V[i,:] /=a
    b1[i] /=a
    for j in range(i+1,N):
        c=V[j,i]
        V[j,:]-=c*V[i,:]
        b1[j]-=c*b1[i]
        
v=empty(N,float)
for i in range(N-1,-1,-1):
    v[i]=b1[i]
    for j in range(i+1,N):
        v[i]-= V[i,j]*v[j]
print('Voltages(V):',v)

Voltages(V): [3.         1.66666667 3.33333333 2.        ]


(b)

The end junctions will have 3 nearby unknown voltages in the equation; the next junction to the end junction will have four currents through it so it will have 4 voltages in the equation, since they are both connected to the known input voltage $V_{+}$ and ground $V_{0}=0$ on the other end. The middle junctions will have five different voltages associated as each current input has a into the proper middle junctions have,lets say for $V_{3}$: $I_{in}=I_{13}+I_{23}$ and $I_{out}=I_{34}+I_{35}$. Each current has $V_3$ associated with it, thus, so $4V_3$, since I am using the convention: $I_{12}=V_{1}-V_{2}$, rest of all voltages for the $V_3$ junction will have a negative sign because of the convention.

Hence, the equations for a middle junction $V_i$ will look like:
$$-V_{i-2}-V_{i-1}+4V_{i}-V_{i+1}-V_{i+2}=0$$

and the end junctions will look like:
$$-V_{n-2}-V_{n-1}+3V_{n}=0$$
$$3V_{1}-V_{2}-V_{3}=V_{+}$$
the nearby junction to the end junction will have:
$$-V_{n-3}-V_{n-2}+4V_{n-1}-V_{n}=0$$
$$-V_{1}+4V_{2}-V_{3}-V_{4}=V_{+}$$

The vector form equation for this circuit will be a diagonal band matrix:
$$\begin{pmatrix}
3 & -1 & -1 & 0 & \cdots & \cdots& \\
-1 & 4 & -1 & -1 & 0 & \cdots & \cdots & \\
 -1 & -1 & 4 &-1&-1&0 \cdots & \cdots & \cdots\\
\vdots & \ddots & \ddots & \ddots  & \ddots &  \\
\vdots &\vdots& -1 &-1&4&-1&-1 \cdots & \cdots\\ 
\vdots &  \vdots& \ddots & \ddots & \cdots-1&-1&4&-1\\
\vdots &\vdots &  \vdots& \ddots & \ddots & \cdots& \cdots -1&-1&3\\
\end{pmatrix}\begin{pmatrix}
v_{1}\\
\vdots \\
\vdots \\
\vdots  \\
v_{n}\\
\end{pmatrix}=\begin{pmatrix}
5 \\
5  \\
0 \\
\vdots\\
\vdots\\
0  \\
\end{pmatrix} $$

(b)

In [12]:
def diagSolver(N):
    
    V=zeros([N,N],float)

    for i in range(2,N-2):
        V[i,i+1]=-1
        V[i,i-1]=-1
        V[i,i-2]=-1
        V[i,i]=4
        V[i+1,i]=-1
        V[i+1,i-1]=-1
        V[i,i+2]=-1
    V[0,0]=3
    V[N-1,N-1]=3
    V[0,1]=-1
    V[0,2]=-1
    V[1,0]=-1
    V[1,2]=-1
    V[1,1]=4
    V[1,3]=-1
    V[N-2,N-1]=-1
    V[N-1,N-3]=-1
    V[N-2,N-4]=-1
    V[N-1,N-2]=-1
    V[N-2,N-2]=4
    
    v2=zeros(N,float)
    v2[0]=v2[1]=5
    print('A:',V,'w:',v2)
    #print(linalg.solve(V,v2))
    for i in range(N):
        a=V[i,i]
        V[i,:] /= a
        v2[i] /= a
        
    
        for j in range(i+1,N):
            b=V[j,i]
            V[j,:]-=b*V[i,:]
            v2[j]-=b*v2[i]
    
    
    v=empty(N,float)
    for i in range(N-1,-1,-1):
        v[i]=v2[i]
        for j in range(i+1,N):
            v[i]-=V[i,j]*v[j]
    print('Voltages(V):',v)
    
    
        

In [13]:
diagSolver(6)

A: [[ 3. -1. -1.  0.  0.  0.]
 [-1.  4. -1. -1.  0.  0.]
 [-1. -1.  4. -1. -1.  0.]
 [ 0. -1. -1.  4. -1. -1.]
 [ 0.  0. -1. -1.  4. -1.]
 [ 0.  0.  0. -1. -1.  3.]] w: [5. 5. 0. 0. 0. 0.]
Voltages(V): [3.7254902  3.43137255 2.74509804 2.25490196 1.56862745 1.2745098 ]


In [14]:
def banded(Aa,va,up,down):#copied from mark newman textbook

    # Copy the inputs and determine the size of the system
    A = copy(Aa)
    v = copy(va)
    N = len(v)

    # Gaussian elimination
    for m in range(N):

        # Normalization factor
        div = A[up,m]

        # Update the vector first
        v[m] /= div
        for k in range(1,down+1):
            if m+k<N:
                v[m+k] -= A[up+k,m]*v[m]

        # Now normalize the pivot row of A and subtract from lower ones
        for i in range(up):
            j = m + up - i
            if j<N:
                A[i,j] /= div
                for k in range(1,down+1):
                    A[i+k,j] -= A[up+k,m]*A[i,j]

    # Backsubstitution
    for m in range(N-2,-1,-1):
        for i in range(up):
            j = m + up - i
            if j<N:
                v[m] -= A[i,j]*v[j]

    return v       

In [15]:
def bandedsolver(N):
    G=empty([5,N],float)#5-diagonals
    G[0,:]=-1
    G[1,:]=-1
    G[2,:]=4
    G[3,:]=-1
    G[4,:]=-1
    G[2,0]=3
    G[2,N-1]=3
    q=zeros(N,float)
    q[0]=q[1]=5
    x=banded(G,q,2,2)
    print('Voltages(V):',x)


In [16]:
bandedsolver(10000)

Voltages(V): [4.99888228e+00 4.99861842e+00 4.99802841e+00 ... 1.97158611e-03
 1.38158071e-03 1.11772227e-03]
